### ISSUE TITLE
CompoundTerm occasionally throws NPE

### ISSUE THREAD

**Issue by freemo** [opennars/opennars#161]
```
java.lang.NullPointerException
	at org.opennars.language.CompoundTerm.cloneTermsDeep(CompoundTerm.java:512)
	at org.opennars.language.CompoundTerm.cloneDeep(CompoundTerm.java:176)
	at org.opennars.language.CompoundTerm.cloneDeep(CompoundTerm.java:31)
	at org.opennars.language.Term.valid(Term.java:416)
	at org.opennars.entity.Sentence.<init>(Sentence.java:181)
	at org.opennars.entity.Sentence.<init>(Sentence.java:83)
	at org.opennars.inference.RuleTables.goalFromQuestion(RuleTables.java:306)
	at org.opennars.inference.RuleTables.reason(RuleTables.java:146)
	at org.opennars.control.GeneralInferenceControl.fireTermlink(GeneralInferenceControl.java:117)
	at org.opennars.control.GeneralInferenceControl.fireTaskLink(GeneralInferenceControl.java:105)
	at org.opennars.control.GeneralInferenceControl.fireConcept(GeneralInferenceControl.java:75)
	at org.opennars.control.GeneralInferenceControl.selectConceptForInference(GeneralInferenceControl.java:53)
	at org.opennars.storage.Memory.cycle(Memory.java:337)
	at org.opennars.main.NAR.cycle(NAR.java:501)
	at org.opennars.main.NAR.addCommand(NAR.java:265)
	at org.opennars.main.NAR.addInput(NAR.java:283)
	at org.opennars.main.NAR.addInputFile(NAR.java:327)
	at org.opennars.core.NALTest.testNAL(NALTest.java:194)
	at org.opennars.core.NALTest.test(NALTest.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by PtrMan** [comment]
Terms should be null at all!

**Comment by PtrMan** [comment]
We need to figure out where the nulls come from
