### ISSUE TITLE
Maven build failure: ClassNotFoundException: net.bytebuddy.dynamic.ModifierResolver

### ISSUE THREAD

**Issue by jorisbontje** [opennars/opennars#62]
With Oracle JDK 1.8.0_74 and commit eee2158297fd19f24366b7019730ca30a71b9973

```
$ mvn install
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.430 s
[INFO] Finished at: 2016-02-15T14:30:16+01:00
[INFO] Final Memory: 29M/404M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-test) on project nars_util: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test failed: There was an error in the forked process
[ERROR] org.testng.TestNGException:
[ERROR]
[ERROR] An error occurred while instantiating class com.github.fge.grappa.matchers.join.JoinMatcherBuildTest: net/bytebuddy/dynamic/ModifierResolver
[ERROR] at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:394)
[ERROR] at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:295)
[ERROR] at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:118)
[ERROR] at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:183)
[ERROR] at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:128)
[ERROR] at org.testng.TestRunner.initMethods(TestRunner.java:416)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:242)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:212)
[ERROR] at org.testng.TestRunner.<init>(TestRunner.java:159)
[ERROR] at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:549)
[ERROR] at org.testng.SuiteRunner.init(SuiteRunner.java:161)
[ERROR] at org.testng.SuiteRunner.<init>(SuiteRunner.java:114)
[ERROR] at org.testng.TestNG.createSuiteRunner(TestNG.java:1290)
[ERROR] at org.testng.TestNG.createSuiteRunners(TestNG.java:1277)
[ERROR] at org.testng.TestNG.runSuitesLocally(TestNG.java:1131)
[ERROR] at org.testng.TestNG.run(TestNG.java:1048)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:224)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: java.lang.NoClassDefFoundError: net/bytebuddy/dynamic/ModifierResolver
[ERROR] at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.<init>(CachingMockBytecodeGenerator.java:20)
[ERROR] at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.<init>(ByteBuddyMockMaker.java:22)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ERROR] at java.lang.Class.newInstance(Class.java:442)
[ERROR] at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:33)
[ERROR] at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:12)
[ERROR] at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:11)
[ERROR] at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:23)
[ERROR] at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:44)
[ERROR] at org.mockito.Mockito.<clinit>(Mockito.java:1101)
[ERROR] at com.github.fge.grappa.matchers.join.JoinMatcherBuildTest.<clinit>(JoinMatcherBuildTest.java:46)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ERROR] at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
[ERROR] at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:382)
[ERROR] ... 22 more
[ERROR] Caused by: java.lang.ClassNotFoundException: net.bytebuddy.dynamic.ModifierResolver
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] ... 42 more
[ERROR] -> [Help 1]
```

**Comment by patham9** [comment]
Sometimes it worked, sometimes it didn't giving arbitrary errors like this and other ones, sometimes it worked on my Linux, sometimes only on my Windows. We had maven issues from time to time and this was one reason why I was very glad that Clojure had a much more reliable and easier to configure build system. :)

**Comment by patham9** [comment]
Maven is not used anymore (altough a Maven-branch, where this issue does not arise, hopefully, anymore, exists)
